import pandas as pd
# df=pd.read_csv("income.csv")
# print(df)
# print(df.age_group.unique())
# print(df.groupby(df.age_group).count())
# print("count program")
# print(df.groupby(df.age_group).count())
# print("min program")
# print(df.groupby(df.age_group).min())
# print("max")
# print(df.groupby(df.age_group).max())
# print("mean")
# print(df.groupby(df.age_group).mean())
# print("std")
# print(df.groupby(df.age_group).std())
# print("describe")
# print(df.groupby(df.age_group).describe())

print("*********************")
from sklearn import datasets
data = datasets.load_iris()
df = pd.DataFrame(data.data,columns=data.feature_names)
df['species'] = pd.Series(data.target)
print(df.head())

print(df.groupby(df.species).count())
print("min purpose")
print(df.groupby(df.species).min())
print("max")
print(df.groupby(df.species).max())
print("mean")
print(df.groupby(df.species).mean())
print("describe")
print(df.groupby(df.species).describe())
print("std")
print(df.groupby(df.species).std())

print("sepal length (cm)")
print(df.groupby(df.species)['sepal length (cm)'].max())